language: node_js
node_js:
  - "11.4.0"
before_script:
  - npm install
script:
  - npm run compile
  - npm run test
  - npm run tslint
  - npm run package
after_success: npm run coverage
deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: ./*.vsix
    skip_cleanup: true
    on:
      tags: true
      #skip pre-release tags
      condition: $TRAVIS_TAG =~ ^v[0-9]+[.][0-9]+[.][0-9]?$
  #- provider: script
  #  script: bash vscode-marketplace-publish.sh
  #  skip_cleanup: true
  #  on:
  #    branch: master
  #    tags: true

